language: node_js
node_js: node
services:
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: "vQO+o5JvI7E6Ml1ZJ9XlOLUzMc3up0gF2aZHzHT5yQO5eOOFodmeYw9a7sxDpOt4suJqSC6RbWLG7VaYn7m2ds0BB3BB1P04QBALlsJHZF7sV4NdVWr1/QfBXSsPgH4BVU5NTma8bk+2Gv80dVOTdksilb+XKIRXZlr45We3eJ2/kD+ihaj7b0ZA+LY+vI3/BaMxfQjrKsiE9j+2gJOJIzcP+vgSxfBP6hvEebvUYI/ly5igvSCCr1vYomxXszsnjKpse4gLnZkyEenTg3FWWpICo/P1XhTrbt82L1hkyu8nQXRINEvTp3sp1B6cD/mLNes3YOPKZqWMwVSBfLslCLmLbbKbzQGRav6WUg6UsM2SJJ9sAN05ZsBVgCNe/eLNzpkr8cdl01/04xP/LMTcEK4vlL81q8jl69ksNa7C1aw1yccfSG6DAe7WE4HKpof5a/rVXdhvzxBYqM8OUbbAUWY+H7Aw/Gg9IlqSNYhuXc3qx+vlNkrnGERp4t+2knb+xsozde8tuk5wwDBP3oFiOwBg20Z6kdL+EcSicTBJnZVEYV36877UhGRf5WGY4jyIL+6CElkbAW9NMJQIC+2oH+kDRxTUZUAhmqhIHfL0Z4CGC5ScwxHWLQPkSL3Yuq01odeFpw10+oHGbfkSittWAJzenRH5feWMKCMnamzoEZw="
    app: evening-wildwood-14893
    on:
      repo: mchinn614/blog-app-mongoose-tests
